apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: thitipun
  namespace: thitipun-dev
spec:
  rules:
  - host: ken-ubuntu.saksiam.corp
    http:
      paths:
      - backend:
          service:
            name: thitipun7024
            port:
              number: 80
        path: /thitipun
        pathType: Prefix
status:
  loadBalancer: {}
